version: '3'

services:
  backend:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development

  frontend:
    build: ./client 
    ports:
      - "3000:80"
    depends_on:
      - backend
