version: '3'

services:
  backend:
    image: saloniarch/poker-hand-backend:v1
    build:
        context: ./server
    platform: linux/amd64
    ports:
      - "3002:3001"


  frontend:
    image: saloniarch/poker-hand-frontend:v1
    build: 
      context: ./client
    platform: linux/amd64
    ports:
      - "3001:80"
    depends_on:
      - backend