version: '3'

services:
  backend:
    build: ./server
    ports:
      - "3002:3001"
    volumes:
      - ./server:/app:cached
      - /app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build: ./client
    ports:
      - "3001:80"
    depends_on:
      - backend
